# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'en-uk'

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Website info
title: Paciran Lamongan
description: The professional publishing platform
cover: assets/images/blog-cover.jpg
logo: assets/images/ciran.jpg
logo_dark: assets/images/box.jpg
favicon: assets/images/box.jpg
production_url: https://www.paciran.com
source_url: https://github.com/paciran/www/
CNAME: www.paciran.com

# Social info
navigation: True # show the navbar links
subscribers: True # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: _paciran # replace by your username
facebook: 113095765373402 # replace by your username

# Disqus
disqus: true
disqus_shortname: paciran1 # replace with your disqus username

# Google Analytics
google_analytics: UA-127077893-1

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: paciran
repo: www
branch: master
relative_source: ../www/
destination: _site/
production_url:  https://www.paciran.com
source_url:  https://github.com/paciran/www/

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
 
compress_html:
  comments: all
  blanklines: true