# Jekyll configuration
markdown: kramdown
language: 'id-ID'
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
highlighter: none
paginate: 50 7# it will paginate after this number
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md,txt"
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
# Website info

title: Paciran ❤ Lamongan
description: "Antara Kebenaran Relatif, Keyakinan dan Kepalsuan"
tagline: "Truth, Faith & Fakes"
url: "https://www.paciran.com"
baseurl: /
cover: assets/images/sunset-di-paciran.jpg
logo: # assets/images/blog-icon.png
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
production_url: https://www.paciran.com
source_url: https://github.com/paciran/www/
CNAME: www.paciran.com

# Social info
navigation: True # show the navbar links
subscribers: False # you need to connect an external service for this to work,
# subscribe: https://paciran.us19.list-manage.com/subscribe/post?u=fe5017783814a21bff3579a15&amp;id=92ceeb0d01
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: _paciran
facebook: pacirandotcom
instagram: paciranmesuwur

# Disqus
disqus: True
disqus_shortname: paciran1 # replace with your disqus username

# Google Analytics
google_analytics: UA-127077893-1

# Permalinks
permalink: /:title
timezone: Indonesia/Jakarta
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed, jekyll-sitemap, jekyll-redirect-from]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: paciran
repo: www
branch: master
relative_source: ../www/
destination: _site/
production_url: https://www.paciran.com
source_url: https://github.com/paciran/www/

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      current: post
      navigation: True
      class: post-template
compress_html:
  clippings: all
  comments: all
  blanklines: true
